<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<RumblePath>G:\SteamLibrary\steamapps\common\RUMBLE</RumblePath>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\obsasset" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\obsasset" />
		<EmbeddedResource Include="Assets\obsasset - Working pre minimal mesh" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LavaGang.MelonLoader" Version="0.7.1" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="G:\SteamLibrary\steamapps\common\RUMBLE\MelonLoader\net6\**\*.dll" Private="false" />
		<Reference Include="G:\SteamLibrary\steamapps\common\RUMBLE\MelonLoader\net35\**\*.dll" Private="false" />
		<Reference Include="G:\SteamLibrary\steamapps\common\RUMBLE\MelonLoader\Il2CppAssemblies\**\*.dll" Private="false" />
		<Reference Include="OBS_Control_API">
			<HintPath>G:\SteamLibrary\steamapps\common\RUMBLE\Mods\OBS_Control_API.dll</HintPath>
		</Reference>
		<Reference Include="RumbleModdingAPI">
			<HintPath>G:\SteamLibrary\steamapps\common\RUMBLE\Mods\RumbleModdingAPI.dll</HintPath>
		</Reference>
		<Reference Include="OBS_Control_API">
			<HintPath>G:\SteamLibrary\steamapps\common\RUMBLE\Mods\UIFramework.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="_Misc\ThunderstorePackage\Mods\" />
	</ItemGroup>

	<Target Name="PreBuild" AfterTargets="PreBuildEvent">
		<Exec Command="taskkill /f /t /im RUMBLE.exe 2&gt;NUL | echo killed rumble" />
	</Target>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		
	</Target>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!--Copy to mods folder-->
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(RumblePath)\Mods&quot;" />
		<!--Copy to thunderstore package-->
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(ProjectDir)_Misc\ThunderstorePackage\Mods&quot;" />
		<Exec Command="COPY &quot;$(ProjectDir)README.md&quot; &quot;$(ProjectDir)_Misc\ThunderstorePackage\&quot;" />
	</Target>
</Project>
